from typing import Any, Callable, TypeVar, overload

F = TypeVar("F", bound=Callable[..., Any])

@overload
def jit(func: F) -> F: ...
@overload
def jit(*args: Any, **kwargs: Any) -> Callable[[F], F]: ...

@overload
def njit(func: F) -> F: ...
@overload
def njit(*args: Any, **kwargs: Any) -> Callable[[F], F]: ...

def prange(*args: Any, **kwargs: Any) -> range: ...
