from typing import Any, Sequence


class RtlSdr:
    sample_rate: float
    center_freq: float
    freq_correction: int
    gain: float

    def __init__(self, device_index: int | None = ...) -> None: ...
    @staticmethod
    def get_device_count() -> int: ...
    @staticmethod
    def get_device_serial_addresses() -> Sequence[str]: ...
    def read_samples(self, num_samples: int) -> Any: ...
    def set_gain_mode(self, auto: bool) -> None: ...
    def close(self) -> None: ...
