from __future__ import annotations

import asyncio
from collections.abc import Sequence
from typing import Any, ClassVar, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from wavecapsdr.capture import CaptureManager
    from wavecapsdr.decoders.lrrp import RadioLocation
    from wavecapsdr.trunking.config import HuntMode, TalkgroupConfig, TrunkingSystemConfig
    from wavecapsdr.trunking.system import ActiveCall, VoiceRecorder
    from wavecapsdr.trunking.voice_channel import VoiceChannel


class TrunkingSystemLike(Protocol):
    cfg: "TrunkingSystemConfig"

    def to_dict(self) -> dict[str, Any]: ...
    def get_active_calls(self) -> list["ActiveCall"]: ...
    def get_all_locations(self) -> list["RadioLocation"]: ...
    def get_messages(self, limit: int = 100, offset: int = 0) -> list[dict[str, Any]]: ...
    def clear_messages(self) -> int: ...
    def get_hunt_mode(self) -> "HuntMode": ...
    def get_locked_frequency(self) -> float | None: ...
    def set_hunt_mode(self, mode: "HuntMode", locked_freq: float | None = None) -> None: ...
    def get_control_channels_info(self) -> list[dict[str, Any]]: ...
    def set_channel_enabled(self, freq_hz: float, enabled: bool) -> None: ...
    def trigger_scan(self) -> dict[float, dict[str, Any]]: ...
    def get_voice_channels(self) -> list["VoiceChannel"]: ...
    def get_voice_channel(self, channel_id: str) -> "VoiceChannel | None": ...
    def get_voice_recorder(self, recorder_id: str) -> "VoiceRecorder | None": ...


class TrunkingManagerLike(Protocol):
    supports_voice_streams: ClassVar[bool]

    def set_capture_manager(self, capture_manager: "CaptureManager") -> None: ...
    def set_config_path(self, config_path: str) -> None: ...
    def register_config(self, config: "TrunkingSystemConfig") -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def add_system(
        self, config: "TrunkingSystemConfig", talkgroups_csv: str | None = None
    ) -> TrunkingSystemLike: ...
    async def remove_system(self, system_id: str) -> None: ...
    async def update_talkgroups(
        self, system_id: str, talkgroups: list["TalkgroupConfig"]
    ) -> tuple[int, int]: ...
    async def clear_messages(self, system_id: str) -> int: ...
    async def set_hunt_mode(
        self, system_id: str, mode: "HuntMode", locked_freq: float | None = None
    ) -> None: ...
    async def set_channel_enabled(self, system_id: str, freq_hz: float, enabled: bool) -> None: ...
    async def trigger_scan(self, system_id: str) -> dict[float, dict[str, Any]]: ...
    async def get_all_locations(self, system_id: str) -> list["RadioLocation"]: ...
    async def start_system(self, system_id: str, persist: bool = True) -> None: ...
    async def stop_system(self, system_id: str, persist: bool = True) -> None: ...
    def list_systems(self) -> Sequence[TrunkingSystemLike]: ...
    def get_system(self, system_id: str) -> TrunkingSystemLike | None: ...
    def get_system_for_capture(self, capture_id: str) -> str | None: ...
    def get_active_calls(self, system_id: str | None = None) -> list["ActiveCall"]: ...
    async def subscribe_events(self) -> asyncio.Queue[dict[str, Any]]: ...
    async def unsubscribe_events(self, queue: asyncio.Queue[dict[str, Any]]) -> None: ...
